name: compact_int_map
homepage: https://shtanko.dev
description: >-
  emory efficient integer map implementation in dart.
version: 0.0.1
repository: https://github.com/ashtanko/compact_int_map

topics:
  - collections
  - data-structures

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  benchmarking: ^0.6.1

dev_dependencies:
  lint: '>=1.5.0 <3.0.0'
  test: ^1.16.4
